site_name: Tutecnoinfor
site_description: 'Soluciones a problemas informaticos'
site_author: 'Ismael Santiago Estévez'
site_url: ''

nav:
  - Inicio: 'index.md'
  - Entradas: 'entradas.md'
  - Informacion: 'informacion.md'

theme: readthedocs